### ISSUE TITLE
Players can dig another's car with driver inside

### ISSUE THREAD

**Issue by amadin** [paramat/mesecar#1]
If first player sit in his own car then second player can dig this car and put in inventory. I think it is thery bad, because car have mese block.

Also my small suggestions:
- Add owner to cars, then players will park their cars near house.
- Set yellow car less bright.
- Replace one of the two pink cars on the white or green
- If player sit in the car then car light up (because cars don't have the light from the headlights).
- Replace mese block by gold block, because mese needed for toools and weapon, but gold use only for armor.

**Comment by HybridDog** [comment]
> […] gold use only for armor.

gold armour is a weak one because gold is fairly soft in comparison to steel, but it is used for representative purposes

> Replace mese block by gold block […]

ln reality gold isn't used for cars, is it? But platinum, which is more expensive, is used as catalyst.

**Comment by paramat** [comment]
Yes the mod is very simple and i'm not really thinking about unpleasant behaviour on servers, someone else can fix that if they want i'm too busy.
Owners .. well it might be nice to be able to share cars.
Mesecar is mese yellow from the original (and best) mese block so can't be changed, the letters on the roof are meant to be a tribute to the original letters.
There's only 1 pink car, i might add more textures later.
Lighting up is not needed (i'm not sure it's possible) it doesn't light up the environment so is not useful.
Mese is a magickal material used for many purposes including as a power source, it is the car's battery, gold cannot produce power.

**Comment by HybridDog** [comment]
> Mese is a magickal material […]

this is wrong, Esem is the magical material, Mese is a sort of science fiction material, aliens brought it
you can get ESEM at the fractured game, there it is available because there is a wizard …
Don't you know the stories?
